name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
        with:
          version: 0.0.0
      - uses: actions/upload-artifact@v4
        with:
          name: build_output
          path: |
            ./output/*.txt
            ./output/*.zip
          retention-days: 7
